name: Docker Image Build for NSI SNMPMon

on:
  workflow_dispatch:
    inputs:
      buildtag:
        description: "Build Tag"
        default: "dev"
        type: "string"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: sdn-sense/nsi-snmpmon
        path: nsi-snmpmon

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    - name: Build the NSI SNMPMon Image
      run: | 
        cd nsi-snmpmon/docker/
        docker build . --file Dockerfile --build-arg ARCH=amd64 --tag sdnsense/nsi-snmpmon:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)

    - name: Docker Push NSI SNMPMon Image with tag and date
      run: docker push sdnsense/nsi-snmpmon:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)

    - name: Docker Push NSI SNMPMon Image with tag
      run: |
        docker tag sdnsense/nsi-snmpmon:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d) sdnsense/nsi-snmpmon:${{ github.event.inputs.buildtag }}
        docker push sdnsense/nsi-snmpmon:${{ github.event.inputs.buildtag }}
